### ISSUE TITLE
Magisk not detected when building from source

### ISSUE THREAD

**Issue by nemirst** [byxiaorun/Ruru#2]
Hey,
I downloaded APK file from releases: [v1.1.0(12)](https://github.com/byxiaorun/Ruru/releases/tag/v1.1.0). It detects Magisk - all is good. Then I tried building from source (tried downloading code from the same release, also via git from branches - new and master) to see which check detected Magisk. Build was successful but resulting app didn't detect Magisk. Do you know what could be the reason?

**Comment by laurismea** [comment]
Nevermind - this is the problem with https://github.com/Dr-TSNG/ApplistDetector which you are using.
